"""Created tables for mind muscle application

Revision ID: 3625c000dcfc
Revises: 
Create Date: 2020-06-17 13:45:54.944034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3625c000dcfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('description'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=60), nullable=False),
                    sa.Column('username', sa.String(
                        length=50), nullable=False),
                    sa.Column('password', sa.String(
                        length=300), nullable=False),
                    sa.Column('privilage', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('workoutplans',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('muscle_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(
                        length=300), nullable=True),
                    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('exercises',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('workoutplan_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.String(
                        length=200), nullable=True),
                    sa.Column('sets', sa.Integer(), nullable=False),
                    sa.Column('reps', sa.Integer(), nullable=False),
                    sa.Column('link', sa.String(length=200), nullable=True),
                    sa.ForeignKeyConstraint(['workoutplan_id'], [
                                            'workoutplans.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    op.drop_table('workoutplans')
    op.drop_table('users')
    op.drop_table('muscles')
    # ### end Alembic commands ###
