"""Added difficulty column for exercises

Revision ID: 0b98626cd4ae
Revises: 3625c000dcfc
Create Date: 2020-06-19 16:03:44.396032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b98626cd4ae'
down_revision = '3625c000dcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column(
        'difficulty', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'difficulty')
    # ### end Alembic commands ###
